repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.337
    hooks:
      - id: pyright
        args: ["--outputjson"]
        additional_dependencies: [pyright==1.1.337]
